language: python
python:
      - '3.6'

before_script:
      - pip install -r requirements.txt

branches:
    only:
        - dev

env: 
      - DJANGO_SETTINGS_MODULE=purbeurre_project.settings.travis
      - SECRET_KEY = "|V<=Y\x0cJ`w'r%XVbey5A,,\x0bsZ"

services:
      - postgresql

script:
      - python manage.py test